stages:
  - build
  - deploy
services:
  - docker:dind
before_script:
  - apk update && apk add --no-cache git
  - docker info

test:
  image: docker:latest
  stage: build
  script: 
    - which docker
    - docker login -u SeanG7 -p $GITLAB_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/seang7/seangilmore .
    - docker push registry.gitlab.com/seang7/seangilmore:latest

deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script: 
    - ssh -t root@seangilmore.xyz "docker stop seangilmore || true && docker rm seangilmore || true && docker login registry.gitlab.com && docker pull registry.gitlab.com/seang7/seangilmore && docker run -d --name seangilmore -e VIRTUAL_HOST=seangilmore.xyz --expose=8080 registry.gitlab.com/seang7/seangilmore"